# Generated by Django 5.0 on 2024-03-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogposts',
            new_name='post',
        ),
    ]
